version: '3'

services:
  ufro_ovdas:
   container_name: ovdas-backend
   image: mysql
   environment:
    MYSQL_DATABASE: ufro_ovdas
    MYSQL_ROOT_PASSWORD: ufro-ovdas
    MYSQL_ROOT_HOST: '%'
   ports:
   - "127.0.0.1:3306:3306"
   restart: always
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./.envs/.mysql
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - ufro_ovdas
