version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 8000
    env_file:
      - ./.envs/.mysql
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - ufro_ovdas
