version: '3'

services:
  trazas:
    #container_name: api_ovdas
    environment:
      DEBUG: 'true'
    restart: always
    build: ./trazas
    expose:
      - "8000"
    env_file:
      - ./.envs/.mysql
    volumes:
      - .:/code
    entrypoint: ""
    command: /usr/local/bin/gunicorn docker_django.wsgi:application -w 2 -b :8000
   #/usr/local/bin/gunicorn docker_django.wsgi:application -w 2 -b :8000
   #/usr/local/lib/python3.8/dist-packages:
